import 'package:cloud_firestore/cloud_firestore.dart';

class DataImportService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  Map<String, dynamic> _getAdmissionTemplate() {
    return {
      'description': 'Admission process and requirements for 2024',
      'descriptionRu': 'Процесс поступления и требования на 2024 год. Для поступления необходимо сдать ЕНТ (Единое национальное тестирование).',
      'descriptionKz': '2024 жылға түсу процесі және талаптар. Түсу үшін Бірыңғай ұлттық тестілеуден (БҰТ) өту қажет.',
      'requirements': [
        {
          'id': 'req1',
          'title': 'High School Diploma',
          'titleRu': 'Аттестат о среднем образовании',
          'titleKz': 'Орта білім туралы куәлік',
          'description': 'Original or notarized copy of high school diploma',
          'descriptionRu': 'Оригинал или нотариально заверенная копия аттестата о среднем образовании',
          'descriptionKz': 'Орта білім туралы куәліктің түпнұсқасы немесе нотариалды расталған көшірмесі',
          'type': 'document'
        },
        {
          'id': 'req2',
          'title': 'UNT Certificate',
          'titleRu': 'Сертификат ЕНТ',
          'titleKz': 'БҰТ сертификаты',
          'description': 'UNT (Unified National Testing) certificate with minimum score of 50 points',
          'descriptionRu': 'Сертификат ЕНТ (Единое национальное тестирование) с минимальным баллом 50',
          'descriptionKz': 'Ең аз 50 ұпаймен БҰТ (Бірыңғай ұлттық тестілеу) сертификаты',
          'type': 'document'
        },
        {
          'id': 'req3',
          'title': 'UNT Subjects',
          'titleRu': 'Предметы ЕНТ',
          'titleKz': 'БҰТ пәндері',
          'description': 'Mathematics, History of Kazakhstan, Kazakh/Russian language, and one profile subject',
          'descriptionRu': 'Математика, История Казахстана, Казахский/Русский язык и один профильный предмет',
          'descriptionKz': 'Математика, Қазақстан тарихы, Қазақ/Орыс тілі және бір профильді пән',
          'type': 'requirement'
        }
      ],
      'procedures': [
        {
          'step': 1,
          'title': 'Take UNT',
          'titleRu': 'Сдать ЕНТ',
          'titleKz': 'БҰТ тапсыру',
          'description': 'Register and take the Unified National Testing (UNT) in June',
          'descriptionRu': 'Зарегистрироваться и сдать Единое национальное тестирование (ЕНТ) в июне',
          'descriptionKz': 'Тіркелу және маусым айында Бірыңғай ұлттық тестілеуден (БҰТ) өту'
        },
        {
          'step': 2,
          'title': 'Submit Application',
          'titleRu': 'Подача заявления',
          'titleKz': 'Өтініш беру',
          'description': 'Submit online application through university website with UNT results',
          'descriptionRu': 'Подать заявление онлайн через сайт университета с результатами ЕНТ',
          'descriptionKz': 'БҰТ нәтижелерімен университет сайты арқылы онлайн өтініш беру'
        },
        {
          'step': 3,
          'title': 'Submit Documents',
          'titleRu': 'Подача документов',
          'titleKz': 'Құжаттарды тапсыру',
          'description': 'Submit required documents: diploma, UNT certificate, identity document',
          'descriptionRu': 'Подать необходимые документы: аттестат, сертификат ЕНТ, удостоверение личности',
          'descriptionKz': 'Қажетті құжаттарды тапсыру: куәлік, БҰТ сертификаты, жеке басын куәландыратын құжат'
        }
      ],
      'deadlines': [
        {
          'id': 'deadline1',
          'program': 'Bachelor Programs',
          'programRu': 'Программы бакалавриата',
          'programKz': 'Бакалавриат бағдарламалары',
          'deadline': Timestamp.fromDate(DateTime(2024, 7, 15)),
          'type': 'application'
        }
      ],
      'scholarships': [
        {
          'id': 'sch1',
          'title': 'Presidential Scholarship',
          'titleRu': 'Президентская стипендия',
          'titleKz': 'Президенттік стипендия',
          'description': 'For students with high UNT scores (120+ points)',
          'descriptionRu': 'Для студентов с высокими баллами ЕНТ (120+ баллов)',
          'descriptionKz': 'Жоғары БҰТ баллдары бар студенттерге (120+ ұпай)',
          'amount': 0.0,
          'currency': 'KZT',
          'coverage': 'full'
        }
      ],
      'financialAid': {
        'description': 'Various financial aid options available',
        'descriptionRu': 'Доступны различные варианты финансовой помощи',
        'descriptionKz': 'Әртүрлі қаржылық көмек нұсқалары қолжетімді',
        'options': ['Scholarships', 'Grants', 'Student loans'],
        'optionsRu': ['Стипендии', 'Гранты', 'Студенческие займы'],
        'optionsKz': ['Стипендиялар', 'Гранттар', 'Студенттік несиелер']
      }
    };
  }

  Map<String, dynamic> _getMissionTemplate(String universityType) {
    final templates = {
      'technical': {
        'text': 'To provide world-class technical education and innovation',
        'textRu': 'Обеспечение технического образования мирового уровня и инноваций',
        'textKz': 'Әлемдік деңгейдегі техникалық білім беру және инновациялар',
        'vision': 'Leading technical university in Central Asia',
        'visionRu': 'Ведущий технический университет Центральной Азии',
        'visionKz': 'Орталық Азиядағы жетекші техникалық университет',
        'values': ['Innovation', 'Excellence', 'Practical Skills'],
        'valuesRu': ['Инновации', 'Превосходство', 'Практические навыки'],
        'valuesKz': ['Инновациялар', 'Тамаша', 'Практикалық дағдылар']
      },
      'medical': {
        'text': 'To provide world-class medical education and healthcare',
        'textRu': 'Обеспечение медицинского образования мирового уровня и здравоохранения',
        'textKz': 'Әлемдік деңгейдегі медициналық білім беру және денсаулық сақтау',
        'vision': 'Leading medical university in Central Asia',
        'visionRu': 'Ведущий медицинский университет Центральной Азии',
        'visionKz': 'Орталық Азиядағы жетекші медициналық университет',
        'values': ['Excellence', 'Compassion', 'Innovation'],
        'valuesRu': ['Превосходство', 'Сострадание', 'Инновации'],
        'valuesKz': ['Тамаша', 'Жанашырлық', 'Инновациялар']
      },
      'pedagogical': {
        'text': 'To provide world-class teacher education',
        'textRu': 'Обеспечение педагогического образования мирового уровня',
        'textKz': 'Әлемдік деңгейдегі педагогикалық білім беру',
        'vision': 'Leading pedagogical university in Central Asia',
        'visionRu': 'Ведущий педагогический университет Центральной Азии',
        'visionKz': 'Орталық Азиядағы жетекші педагогикалық университет',
        'values': ['Excellence', 'Dedication', 'Innovation'],
        'valuesRu': ['Превосходство', 'Преданность', 'Инновации'],
        'valuesKz': ['Тамаша', 'Арқа сүю', 'Инновациялар']
      },
      'economic': {
        'text': 'To provide world-class business and economic education',
        'textRu': 'Обеспечение бизнес и экономического образования мирового уровня',
        'textKz': 'Әлемдік деңгейдегі бизнес және экономикалық білім беру',
        'vision': 'Leading business school in Central Asia',
        'visionRu': 'Ведущая бизнес-школа Центральной Азии',
        'visionKz': 'Орталық Азиядағы жетекші бизнес-мектебі',
        'values': ['Business Excellence', 'Innovation', 'Entrepreneurship'],
        'valuesRu': ['Превосходство в бизнесе', 'Инновации', 'Предпринимательство'],
        'valuesKz': ['Бизнесте тамаша', 'Инновациялар', 'Кәсіпкерлік']
      },
      'humanitarian': {
        'text': 'To provide world-class humanitarian education',
        'textRu': 'Обеспечение гуманитарного образования мирового уровня',
        'textKz': 'Әлемдік деңгейдегі гуманитарлық білім беру',
        'vision': 'Leading humanitarian university in Central Asia',
        'visionRu': 'Ведущий гуманитарный университет Центральной Азии',
        'visionKz': 'Орталық Азиядағы жетекші гуманитарлық университет',
        'values': ['Excellence', 'Humanity', 'Innovation'],
        'valuesRu': ['Превосходство', 'Гуманность', 'Инновации'],
        'valuesKz': ['Тамаша', 'Адамгершілік', 'Инновациялар']
      },
      'agricultural': {
        'text': 'To provide world-class agricultural education and research',
        'textRu': 'Обеспечение аграрного образования и исследований мирового уровня',
        'textKz': 'Әлемдік деңгейдегі аграрлық білім беру және зерттеулер',
        'vision': 'Leading agricultural university in Central Asia',
        'visionRu': 'Ведущий аграрный университет Центральной Азии',
        'visionKz': 'Орталық Азиядағы жетекші аграрлық университет',
        'values': ['Sustainability', 'Innovation', 'Excellence'],
        'valuesRu': ['Устойчивость', 'Инновации', 'Превосходство'],
        'valuesKz': ['Тұрақтылық', 'Инновациялар', 'Тамаша']
      },
      'arts': {
        'text': 'To provide world-class arts education',
        'textRu': 'Обеспечение художественного образования мирового уровня',
        'textKz': 'Әлемдік деңгейдегі көркем білім беру',
        'vision': 'Leading arts university in Central Asia',
        'visionRu': 'Ведущий художественный университет Центральной Азии',
        'visionKz': 'Орталық Азиядағы жетекші көркем университет',
        'values': ['Creativity', 'Excellence', 'Innovation'],
        'valuesRu': ['Творчество', 'Превосходство', 'Инновации'],
        'valuesKz': ['Шығармашылық', 'Тамаша', 'Инновациялар']
      },
    };

    return templates[universityType] ?? {
      'text': 'To provide world-class education',
      'textRu': 'Обеспечение образования мирового уровня',
      'textKz': 'Әлемдік деңгейдегі білім беру',
      'vision': 'Leading university in Central Asia',
      'visionRu': 'Ведущий университет Центральной Азии',
      'visionKz': 'Орталық Азиядағы жетекші университет',
      'values': ['Excellence', 'Innovation', 'Integrity'],
      'valuesRu': ['Превосходство', 'Инновации', 'Честность'],
      'valuesKz': ['Тамаша', 'Инновациялар', 'Адалдық']
    };
  }

  Map<String, dynamic> _getHistoryTemplate(String nameRu, int foundedYear) {
    return {
      'text': 'Founded in $foundedYear',
      'textRu': 'Основан в $foundedYear году. $nameRu является одним из ведущих образовательных учреждений Казахстана.',
      'textKz': '$foundedYear жылы құрылды. $nameRu Қазақстандағы жетекші білім беру мекемелерінің бірі.',
      'events': [
        {
          'year': foundedYear,
          'description': 'University founded',
          'descriptionRu': 'Основан университет',
          'descriptionKz': 'Университет құрылды'
        }
      ]
    };
  }

  Map<String, dynamic> _getLeadershipTemplate() {
    return {
      'rectorName': 'Rector',
      'rectorNameRu': 'Ректор',
      'rectorNameKz': 'Ректор',
      'rectorBio': 'University Rector',
      'rectorBioRu': 'Ректор университета',
      'rectorBioKz': 'Университет ректоры',
      'rectorPhotoUrl': '',
      'leaders': []
    };
  }

  Map<String, dynamic> _getInternationalCooperationTemplate() {
    return {
      'description': 'Active international cooperation with partner universities worldwide',
      'descriptionRu': 'Активное международное сотрудничество с партнерскими университетами по всему миру',
      'descriptionKz': 'Әлем бойынша серіктес университеттермен белсенді халықаралық ынтымақтастық',
      'exchangePrograms': [
        {
          'id': 'ex1',
          'name': 'Erasmus+',
          'nameRu': 'Эразмус+',
          'nameKz': 'Эразмус+',
          'description': 'Student exchange program with European universities',
          'descriptionRu': 'Программа обмена студентами с европейскими университетами',
          'descriptionKz': 'Еуропалық университеттермен студенттер алмасу бағдарламасы',
          'country': 'European Union',
          'duration': '1 semester',
          'requirements': 'GPA 3.0+, language certificate',
          'requirementsRu': 'GPA 3.0+, языковой сертификат',
          'requirementsKz': 'GPA 3.0+, тілдік сертификат'
        }
      ],
      'partnerUniversities': [
        {
          'id': 'partner1',
          'name': 'International Partner Universities',
          'country': 'Various',
          'logoUrl': '',
          'website': '',
          'description': 'Partnership in research and student exchange',
          'descriptionRu': 'Партнерство в области исследований и обмена студентами',
          'descriptionKz': 'Зерттеулер және студенттер алмасу саласындағы серіктестік'
        }
      ],
      'opportunities': [
        {
          'id': 'opp1',
          'title': 'International Exchange Programs',
          'titleRu': 'Международные программы обмена',
          'titleKz': 'Халықаралық алмасу бағдарламалары',
          'description': 'Opportunities for student exchange and study abroad',
          'descriptionRu': 'Возможности для обмена студентами и обучения за рубежом',
          'descriptionKz': 'Студенттер алмасу және шетелде оқу мүмкіндіктері',
          'type': 'exchange'
        }
      ]
    };
  }

  Future<void> addUniversities() async {
    final universities = _getUniversitiesData();

    for (final entry in universities.entries) {
      try {
        await _firestore
            .collection('universities')
            .doc(entry.key)
            .set(entry.value);
      } catch (e) {
        throw Exception('Ошибка при добавлении ${entry.key}: $e');
      }
    }
  }

  Map<String, Map<String, dynamic>> _getUniversitiesData() {
    return {
      'kaznu': {
        'name': 'Al-Farabi Kazakh National University',
        'nameRu': 'Казахский национальный университет имени аль-Фараби',
        'nameKz': 'Әл-Фараби атындағы Қазақ ұлттық университеті',
        'description': 'Leading research university in Kazakhstan, founded in 1934',
        'descriptionRu': 'Ведущий исследовательский университет Казахстана, основанный в 1934 году. Один из старейших и наиболее престижных вузов страны.',
        'descriptionKz': '1934 жылы құрылған Қазақстандағы жетекші зерттеу университеті. Елдегі ең ескі және беделді жоғары оқу орындарының бірі.',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kaznu.kz',
        'email': 'info@kaznu.kz',
        'phone': '+7 (727) 377-33-33',
        'rating': 4.8,
        'studentCount': 25000,
        'foundedDate': Timestamp.fromDate(DateTime(1934, 1, 15)),
        'images': [],
        'mission': {
          'text': 'To provide world-class education and conduct cutting-edge research',
          'textRu': 'Обеспечение мирового уровня образования и проведение передовых научных исследований',
          'textKz': 'Әлемдік деңгейдегі білім беру және алдыңғы қатарлы ғылыми зерттеулер жүргізу',
          'vision': 'To become a leading research university in Central Asia',
          'visionRu': 'Стать ведущим исследовательским университетом Центральной Азии',
          'visionKz': 'Орталық Азиядағы жетекші зерттеу университетіне айналу',
          'values': ['Excellence', 'Innovation', 'Integrity', 'Internationalization'],
          'valuesRu': ['Превосходство', 'Инновации', 'Честность', 'Интернационализация'],
          'valuesKz': ['Тамаша', 'Инновациялар', 'Адалдық', 'Интернационализация']
        },
        'history': {
          'text': 'Founded in 1934 as Kazakh State University',
          'textRu': 'Основан в 1934 году как Казахский государственный университет. В 1991 году переименован в честь великого ученого аль-Фараби.',
          'textKz': '1934 жылы Қазақ мемлекеттік университеті ретінде құрылды. 1991 жылы ұлы ғалым Әл-Фараби атында аталды.',
          'events': [
            {
              'year': 1934,
              'description': 'University founded as Kazakh State University',
              'descriptionRu': 'Основан Казахский государственный университет',
              'descriptionKz': 'Қазақ мемлекеттік университеті құрылды'
            },
            {
              'year': 1991,
              'description': 'Renamed after al-Farabi',
              'descriptionRu': 'Переименован в честь аль-Фараби',
              'descriptionKz': 'Әл-Фараби атында аталды'
            }
          ]
        },
        'leadership': {
          'rectorName': 'Galym Mutanov',
          'rectorNameRu': 'Галым Мутанов',
          'rectorNameKz': 'Ғалым Мұтанов',
          'rectorBio': 'Doctor of Technical Sciences, Professor, Academician',
          'rectorBioRu': 'Доктор технических наук, профессор, академик. Руководит университетом с 2007 года.',
          'rectorBioKz': 'Техника ғылымдарының докторы, профессор, академик. 2007 жылдан бастап университетті басқарады.',
          'rectorPhotoUrl': '',
          'leaders': []
        },
        'achievements': [
          {
            'id': 'ach1',
            'title': 'QS World University Rankings',
            'titleRu': 'Рейтинг QS World University Rankings',
            'titleKz': 'QS World University Rankings рейтингі',
            'description': 'Ranked in top 200 universities worldwide',
            'descriptionRu': 'Входит в топ-200 университетов мира по версии QS',
            'descriptionKz': 'QS нұсқасы бойынша әлемдегі топ-200 университеттер қатарына кіреді',
            'imageUrl': '',
            'date': Timestamp.fromDate(DateTime(2023, 6, 1))
          }
        ],
        'academicPrograms': [
          {
            'id': 'prog1',
            'name': 'Computer Science',
            'nameRu': 'Информатика',
            'nameKz': 'Информатика',
            'description': 'Bachelor program in Computer Science and Software Engineering',
            'descriptionRu': 'Программа бакалавриата по информатике и программной инженерии',
            'descriptionKz': 'Информатика және бағдарламалық инженерия бойынша бакалавриат бағдарламасы',
            'degree': 'Bachelor',
            'degreeRu': 'Бакалавр',
            'degreeKz': 'Бакалавр',
            'faculty': 'Faculty of Information Technology',
            'facultyRu': 'Факультет информационных технологий',
            'facultyKz': 'Ақпараттық технологиялар факультеті',
            'duration': 4,
            'language': 'Kazakh, Russian, English',
            'languageRu': 'Казахский, Русский, Английский',
            'languageKz': 'Қазақ, Орыс, Ағылшын',
            'tuitionFee': 500000.0,
            'currency': 'KZT',
            'requirements': [
              'High school diploma',
              'Entrance exam in Mathematics and Physics',
              'English language certificate (for English track)'
            ],
            'requirementsRu': [
              'Аттестат о среднем образовании',
              'Вступительные экзамены по математике и физике',
              'Сертификат по английскому языку (для англоязычного потока)'
            ],
            'requirementsKz': [
              'Орта білім туралы куәлік',
              'Математика және физика бойынша кіру емтихандары',
              'Ағылшын тілі сертификаты (ағылшын тілдік ағым үшін)'
            ],
            'careerOpportunities': [
              'Software Developer',
              'Data Scientist',
              'System Analyst',
              'IT Project Manager'
            ],
            'careerOpportunitiesRu': [
              'Разработчик программного обеспечения',
              'Специалист по данным',
              'Системный аналитик',
              'IT-менеджер проектов'
            ],
            'careerOpportunitiesKz': [
              'Бағдарламалық жасақтаманы дамытушы',
              'Деректер маманы',
              'Жүйелік аналитик',
              'IT-жобалар менеджері'
            ],
            'imageUrl': '',
            'programCategory': 'engineering'
          }
        ],
        'internationalCooperation': {
          'description': 'Active international cooperation with 300+ partner universities',
          'descriptionRu': 'Активное международное сотрудничество с более чем 300 партнерскими университетами по всему миру',
          'descriptionKz': 'Әлем бойынша 300-ден астам серіктес университеттермен белсенді халықаралық ынтымақтастық',
          'exchangePrograms': [
            {
              'id': 'ex1',
              'name': 'Erasmus+',
              'nameRu': 'Эразмус+',
              'nameKz': 'Эразмус+',
              'description': 'Student exchange program with European universities',
              'descriptionRu': 'Программа обмена студентами с европейскими университетами',
              'descriptionKz': 'Еуропалық университеттермен студенттер алмасу бағдарламасы',
              'country': 'European Union',
              'duration': '1 semester',
              'requirements': 'GPA 3.0+, language certificate',
              'requirementsRu': 'GPA 3.0+, языковой сертификат',
              'requirementsKz': 'GPA 3.0+, тілдік сертификат'
            }
          ],
          'partnerUniversities': [
            {
              'id': 'partner1',
              'name': 'Moscow State University',
              'country': 'Russia',
              'logoUrl': '',
              'website': 'https://www.msu.ru',
              'description': 'Partnership in research and student exchange',
              'descriptionRu': 'Партнерство в области исследований и обмена студентами',
              'descriptionKz': 'Зерттеулер және студенттер алмасу саласындағы серіктестік'
            }
          ],
          'opportunities': [
            {
              'id': 'opp1',
              'title': 'Scholarship for International Students',
              'titleRu': 'Стипендия для иностранных студентов',
              'titleKz': 'Шетелдік студенттерге стипендия',
              'description': 'Full tuition coverage for outstanding international students',
              'descriptionRu': 'Полное покрытие обучения для выдающихся иностранных студентов',
              'descriptionKz': 'Керемет шетелдік студенттерге оқу толық қамтамасыз ету',
              'type': 'scholarship'
            }
          ]
        },
        'admission': {
          'description': 'Admission process and requirements for 2024',
          'descriptionRu': 'Процесс поступления и требования на 2024 год. Для поступления необходимо сдать ЕНТ (Единое национальное тестирование).',
          'descriptionKz': '2024 жылға түсу процесі және талаптар. Түсу үшін Бірыңғай ұлттық тестілеуден (БҰТ) өту қажет.',
          'requirements': [
            {
              'id': 'req1',
              'title': 'High School Diploma',
              'titleRu': 'Аттестат о среднем образовании',
              'titleKz': 'Орта білім туралы куәлік',
              'description': 'Original or notarized copy of high school diploma',
              'descriptionRu': 'Оригинал или нотариально заверенная копия аттестата о среднем образовании',
              'descriptionKz': 'Орта білім туралы куәліктің түпнұсқасы немесе нотариалды расталған көшірмесі',
              'type': 'document'
            },
            {
              'id': 'req2',
              'title': 'UNT Certificate',
              'titleRu': 'Сертификат ЕНТ',
              'titleKz': 'БҰТ сертификаты',
              'description': 'UNT (Unified National Testing) certificate with minimum score of 50 points',
              'descriptionRu': 'Сертификат ЕНТ (Единое национальное тестирование) с минимальным баллом 50',
              'descriptionKz': 'Ең аз 50 ұпаймен БҰТ (Бірыңғай ұлттық тестілеу) сертификаты',
              'type': 'document'
            },
            {
              'id': 'req3',
              'title': 'UNT Subjects',
              'titleRu': 'Предметы ЕНТ',
              'titleKz': 'БҰТ пәндері',
              'description': 'Mathematics, History of Kazakhstan, Kazakh/Russian language, and one profile subject',
              'descriptionRu': 'Математика, История Казахстана, Казахский/Русский язык и один профильный предмет',
              'descriptionKz': 'Математика, Қазақстан тарихы, Қазақ/Орыс тілі және бір профильді пән',
              'type': 'requirement'
            }
          ],
          'procedures': [
            {
              'step': 1,
              'title': 'Take UNT',
              'titleRu': 'Сдать ЕНТ',
              'titleKz': 'БҰТ тапсыру',
              'description': 'Register and take the Unified National Testing (UNT) in June',
              'descriptionRu': 'Зарегистрироваться и сдать Единое национальное тестирование (ЕНТ) в июне',
              'descriptionKz': 'Тіркелу және маусым айында Бірыңғай ұлттық тестілеуден (БҰТ) өту'
            },
            {
              'step': 2,
              'title': 'Submit Application',
              'titleRu': 'Подача заявления',
              'titleKz': 'Өтініш беру',
              'description': 'Submit online application through university website with UNT results',
              'descriptionRu': 'Подать заявление онлайн через сайт университета с результатами ЕНТ',
              'descriptionKz': 'БҰТ нәтижелерімен университет сайты арқылы онлайн өтініш беру'
            },
            {
              'step': 3,
              'title': 'Submit Documents',
              'titleRu': 'Подача документов',
              'titleKz': 'Құжаттарды тапсыру',
              'description': 'Submit required documents: diploma, UNT certificate, identity document',
              'descriptionRu': 'Подать необходимые документы: аттестат, сертификат ЕНТ, удостоверение личности',
              'descriptionKz': 'Қажетті құжаттарды тапсыру: куәлік, БҰТ сертификаты, жеке басын куәландыратын құжат'
            }
          ],
          'deadlines': [
            {
              'id': 'deadline1',
              'program': 'Bachelor Programs',
              'programRu': 'Программы бакалавриата',
              'programKz': 'Бакалавриат бағдарламалары',
              'deadline': Timestamp.fromDate(DateTime(2024, 7, 15)),
              'type': 'application'
            }
          ],
          'scholarships': [
            {
              'id': 'sch1',
              'name': 'Presidential Scholarship',
              'nameRu': 'Президентская стипендия',
              'nameKz': 'Президенттік стипендия',
              'description': 'Full tuition coverage for outstanding students',
              'descriptionRu': 'Полное покрытие обучения для выдающихся студентов',
              'descriptionKz': 'Керемет студенттерге оқу толық қамтамасыз ету',
              'amount': 100000.0,
              'currency': 'KZT',
              'coverage': 'Full tuition + monthly stipend',
              'coverageRu': 'Полное покрытие обучения + ежемесячная стипендия',
              'coverageKz': 'Оқу толық қамтамасыз ету + ай сайынғы стипендия',
              'requirements': ['GPA 3.8+', 'Active participation in research'],
              'requirementsRu': ['GPA 3.8+', 'Активное участие в научных исследованиях'],
              'requirementsKz': ['GPA 3.8+', 'Ғылыми зерттеулерде белсенді қатысу']
            }
          ],
          'financialAid': {
            'description': 'Various financial aid options available',
            'descriptionRu': 'Доступны различные варианты финансовой помощи',
            'descriptionKz': 'Қаржылық көмектің әртүрлі нұсқалары қолжетімді',
            'options': ['Student loans with low interest', 'Payment plans'],
            'optionsRu': ['Студенческие займы с низкой процентной ставкой', 'Планы оплаты'],
            'optionsKz': ['Төмен пайыздық мөлшерлемесі бар студенттік несиелер', 'Төлем жоспарлары']
          }
        },
        'tour3dUrl': '',
        'universityType': 'comprehensive',
        'latitude': 43.2220,
        'longitude': 76.8512
      },
      'kbtu': {
        'name': 'Kazakh-British Technical University',
        'nameRu': 'Казахско-Британский технический университет',
        'nameKz': 'Қазақ-Британ техникалық университеті',
        'description': 'Leading technical university in Kazakhstan',
        'descriptionRu': 'Ведущий технический университет Казахстана, специализирующийся на инженерии и технологиях',
        'descriptionKz': 'Инженерия мен технологияларға маманданған Қазақстандағы жетекші техникалық университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kbtu.kz',
        'email': 'info@kbtu.kz',
        'phone': '+7 (727) 357-42-27',
        'rating': 4.7,
        'studentCount': 8000,
        'foundedDate': Timestamp.fromDate(DateTime(2001, 1, 1)),
        'images': [],
        'mission': {
          'text': 'To provide world-class technical education',
          'textRu': 'Обеспечение технического образования мирового уровня',
          'textKz': 'Әлемдік деңгейдегі техникалық білім беру',
          'vision': 'To become a leading technical university in Central Asia',
          'visionRu': 'Стать ведущим техническим университетом Центральной Азии',
          'visionKz': 'Орталық Азиядағы жетекші техникалық университетіне айналу',
          'values': ['Innovation', 'Excellence', 'Practical Skills'],
          'valuesRu': ['Инновации', 'Превосходство', 'Практические навыки'],
          'valuesKz': ['Инновациялар', 'Тамаша', 'Практикалық дағдылар']
        },
        'history': {
          'text': 'Founded in 2001 as a joint Kazakh-British project',
          'textRu': 'Основан в 2001 году как совместный казахско-британский проект',
          'textKz': '2001 жылы қазақ-британдық бірлескен жоба ретінде құрылды',
          'events': [
            {
              'year': 2001,
              'description': 'University founded',
              'descriptionRu': 'Основан университет',
              'descriptionKz': 'Университет құрылды'
            }
          ]
        },
        'leadership': {
          'rectorName': 'Kuanyshbek Yessekeyev',
          'rectorNameRu': 'Куанышбек Есекеев',
          'rectorNameKz': 'Қуанышбек Есекеев',
          'rectorBio': 'Doctor of Technical Sciences',
          'rectorBioRu': 'Доктор технических наук',
          'rectorBioKz': 'Техника ғылымдарының докторы',
          'rectorPhotoUrl': '',
          'leaders': []
        },
        'achievements': [],
        'academicPrograms': [
          {
            'id': 'prog1',
            'name': 'Petroleum Engineering',
            'nameRu': 'Нефтегазовое дело',
            'nameKz': 'Мұнай-газ ісі',
            'description': 'Bachelor program in Petroleum Engineering',
            'descriptionRu': 'Программа бакалавриата по нефтегазовому делу',
            'descriptionKz': 'Мұнай-газ ісі бойынша бакалавриат бағдарламасы',
            'degree': 'Bachelor',
            'degreeRu': 'Бакалавр',
            'degreeKz': 'Бакалавр',
            'faculty': 'School of Energy and Oil & Gas Industry',
            'facultyRu': 'Школа энергетики и нефтегазовой промышленности',
            'facultyKz': 'Энергетика және мұнай-газ өнеркәсібі мектебі',
            'duration': 4,
            'language': 'English',
            'languageRu': 'Английский',
            'languageKz': 'Ағылшын',
            'tuitionFee': 1200000.0,
            'currency': 'KZT',
            'requirements': ['High school diploma', 'IELTS 6.0+', 'Entrance exam in Mathematics and Physics'],
            'requirementsRu': ['Аттестат о среднем образовании', 'IELTS 6.0+', 'Вступительные экзамены по математике и физике'],
            'requirementsKz': ['Орта білім туралы куәлік', 'IELTS 6.0+', 'Математика және физика бойынша кіру емтихандары'],
            'careerOpportunities': ['Petroleum Engineer', 'Drilling Engineer', 'Reservoir Engineer'],
            'careerOpportunitiesRu': ['Инженер-нефтяник', 'Инженер по бурению', 'Инженер по разработке месторождений'],
            'careerOpportunitiesKz': ['Мұнай инженері', 'Бұрғылау инженері', 'Кен орындарын игеру инженері'],
            'imageUrl': '',
            'programCategory': 'engineering'
          }
        ],
        'internationalCooperation': {
          'description': 'Partnership with British universities',
          'descriptionRu': 'Партнерство с британскими университетами',
          'descriptionKz': 'Британдық университеттермен серіктестік',
          'exchangePrograms': [],
          'partnerUniversities': [],
          'opportunities': []
        },
        'admission': {
          'description': 'Admission information',
          'descriptionRu': 'Информация о поступлении',
          'descriptionKz': 'Түсу ақпараты',
          'requirements': [],
          'procedures': [],
          'deadlines': [],
          'scholarships': [],
          'financialAid': {
            'description': '',
            'descriptionRu': '',
            'descriptionKz': '',
            'options': [],
            'optionsRu': [],
            'optionsKz': []
          }
        },
        'tour3dUrl': '',
        'universityType': 'technical',
        'latitude': 43.2200,
        'longitude': 76.8500
      },
      'enu': {
        'name': 'L.N. Gumilyov Eurasian National University',
        'nameRu': 'Евразийский национальный университет имени Л.Н. Гумилева',
        'nameKz': 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті',
        'description': 'Leading university in Astana',
        'descriptionRu': 'Ведущий университет Астаны, основанный в 1996 году',
        'descriptionKz': '1996 жылы құрылған Астанадағы жетекші университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Astana, Kazakhstan',
        'city': 'Астана',
        'website': 'https://www.enu.kz',
        'email': 'info@enu.kz',
        'phone': '+7 (7172) 70-95-10',
        'rating': 4.6,
        'studentCount': 15000,
        'foundedDate': Timestamp.fromDate(DateTime(1996, 5, 23)),
        'images': [],
        'mission': {
          'text': 'To provide quality education',
          'textRu': 'Обеспечение качественного образования',
          'textKz': 'Сапалы білім беру',
          'vision': 'Leading university in Kazakhstan',
          'visionRu': 'Ведущий университет Казахстана',
          'visionKz': 'Қазақстандағы жетекші университет',
          'values': ['Quality', 'Innovation'],
          'valuesRu': ['Качество', 'Инновации'],
          'valuesKz': ['Сапа', 'Инновациялар']
        },
        'history': {
          'text': 'Founded in 1996',
          'textRu': 'Основан в 1996 году',
          'textKz': '1996 жылы құрылды',
          'events': []
        },
        'leadership': {
          'rectorName': 'Yerlan Sydykov',
          'rectorNameRu': 'Ерлан Сыдыков',
          'rectorNameKz': 'Ерлан Сыдықов',
          'rectorBio': 'Doctor of Sciences',
          'rectorBioRu': 'Доктор наук',
          'rectorBioKz': 'Ғылым докторы',
          'rectorPhotoUrl': '',
          'leaders': []
        },
        'achievements': [],
        'academicPrograms': [
          {
            'id': 'prog1',
            'name': 'Economics',
            'nameRu': 'Экономика',
            'nameKz': 'Экономика',
            'description': 'Bachelor program in Economics',
            'descriptionRu': 'Программа бакалавриата по экономике',
            'descriptionKz': 'Экономика бойынша бакалавриат бағдарламасы',
            'degree': 'Bachelor',
            'degreeRu': 'Бакалавр',
            'degreeKz': 'Бакалавр',
            'faculty': 'Faculty of Economics',
            'facultyRu': 'Экономический факультет',
            'facultyKz': 'Экономикалық факультет',
            'duration': 4,
            'language': 'Kazakh, Russian',
            'languageRu': 'Казахский, Русский',
            'languageKz': 'Қазақ, Орыс',
            'tuitionFee': 400000.0,
            'currency': 'KZT',
            'requirements': ['High school diploma', 'Entrance exam'],
            'requirementsRu': ['Аттестат о среднем образовании', 'Вступительные экзамены'],
            'requirementsKz': ['Орта білім туралы куәлік', 'Кіру емтихандары'],
            'careerOpportunities': ['Economist', 'Financial Analyst'],
            'careerOpportunitiesRu': ['Экономист', 'Финансовый аналитик'],
            'careerOpportunitiesKz': ['Экономист', 'Қаржылық аналитик'],
            'imageUrl': '',
            'programCategory': 'business'
          }
        ],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'comprehensive',
        'latitude': 51.1694,
        'longitude': 71.4491
      },
      'kimep': {
        'name': 'KIMEP University',
        'nameRu': 'Университет КИМЭП',
        'nameKz': 'КИМЭП университеті',
        'description': 'Leading business university in Kazakhstan',
        'descriptionRu': 'Ведущий бизнес-университет Казахстана, специализирующийся на бизнесе и экономике',
        'descriptionKz': 'Бизнес пен экономикаға маманданған Қазақстандағы жетекші бизнес-университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kimep.kz',
        'email': 'info@kimep.kz',
        'phone': '+7 (727) 270-42-00',
        'rating': 4.5,
        'studentCount': 5000,
        'foundedDate': Timestamp.fromDate(DateTime(1992, 1, 1)),
        'images': [],
        'mission': {
          'text': 'To provide world-class business education',
          'textRu': 'Обеспечение бизнес-образования мирового уровня',
          'textKz': 'Әлемдік деңгейдегі бизнес-білім беру',
          'vision': 'Leading business school in Central Asia',
          'visionRu': 'Ведущая бизнес-школа Центральной Азии',
          'visionKz': 'Орталық Азиядағы жетекші бизнес-мектебі',
          'values': ['Business Excellence', 'Innovation'],
          'valuesRu': ['Превосходство в бизнесе', 'Инновации'],
          'valuesKz': ['Бизнесте тамаша', 'Инновациялар']
        },
        'history': {
          'text': 'Founded in 1992',
          'textRu': 'Основан в 1992 году',
          'textKz': '1992 жылы құрылды',
          'events': []
        },
        'leadership': {
          'rectorName': 'Chan Young Bang',
          'rectorNameRu': 'Чан Ён Бан',
          'rectorNameKz': 'Чан Ён Бан',
          'rectorBio': 'President of KIMEP University',
          'rectorBioRu': 'Президент университета КИМЭП',
          'rectorBioKz': 'КИМЭП университетінің президенті',
          'rectorPhotoUrl': '',
          'leaders': []
        },
        'achievements': [],
        'academicPrograms': [
          {
            'id': 'prog1',
            'name': 'Business Administration',
            'nameRu': 'Бизнес-администрирование',
            'nameKz': 'Бизнес-администрирование',
            'description': 'MBA program',
            'descriptionRu': 'Программа MBA',
            'descriptionKz': 'MBA бағдарламасы',
            'degree': 'Master',
            'degreeRu': 'Магистр',
            'degreeKz': 'Магистр',
            'faculty': 'Bang College of Business',
            'facultyRu': 'Бизнес-колледж Банга',
            'facultyKz': 'Бан бизнес-колледжі',
            'duration': 2,
            'language': 'English',
            'languageRu': 'Английский',
            'languageKz': 'Ағылшын',
            'tuitionFee': 2000000.0,
            'currency': 'KZT',
            'requirements': ['Bachelor degree', 'GMAT or GRE', 'Work experience', 'IELTS 6.5+'],
            'requirementsRu': ['Диплом бакалавра', 'GMAT или GRE', 'Опыт работы', 'IELTS 6.5+'],
            'requirementsKz': ['Бакалавр дипломы', 'GMAT немесе GRE', 'Жұмыс тәжірибесі', 'IELTS 6.5+'],
            'careerOpportunities': ['Business Manager', 'Entrepreneur', 'Consultant'],
            'careerOpportunitiesRu': ['Бизнес-менеджер', 'Предприниматель', 'Консультант'],
            'careerOpportunitiesKz': ['Бизнес-менеджер', 'Кәсіпкер', 'Кеңесші'],
            'imageUrl': '',
            'programCategory': 'business'
          }
        ],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'economic',
        'latitude': 43.2100,
        'longitude': 76.8400
      },
      'sdu': {
        'name': 'Suleyman Demirel University',
        'nameRu': 'Университет имени Сулеймана Демиреля',
        'nameKz': 'Сүлейман Демирел атындағы университет',
        'description': 'Private university in Kaskelen',
        'descriptionRu': 'Частный университет в Каскелене, основанный в 1996 году',
        'descriptionKz': '1996 жылы құрылған Қаскелендегі жеке университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Kaskelen, Kazakhstan',
        'city': 'Қаскелен',
        'website': 'https://www.sdu.edu.kz',
        'email': 'info@sdu.edu.kz',
        'phone': '+7 (727) 307-95-60',
        'rating': 4.4,
        'studentCount': 12000,
        'foundedDate': Timestamp.fromDate(DateTime(1996, 1, 1)),
        'images': [],
        'mission': {
          'text': 'To provide quality education',
          'textRu': 'Обеспечение качественного образования',
          'textKz': 'Сапалы білім беру',
          'vision': 'Leading private university',
          'visionRu': 'Ведущий частный университет',
          'visionKz': 'Жетекші жеке университет',
          'values': ['Quality', 'Innovation'],
          'valuesRu': ['Качество', 'Инновации'],
          'valuesKz': ['Сапа', 'Инновациялар']
        },
        'history': {
          'text': 'Founded in 1996',
          'textRu': 'Основан в 1996 году',
          'textKz': '1996 жылы құрылды',
          'events': []
        },
        'leadership': {
          'rectorName': 'Assylbek Kozhakhmetov',
          'rectorNameRu': 'Асылбек Кожахметов',
          'rectorNameKz': 'Асылбек Қожахметов',
          'rectorBio': 'Rector of SDU',
          'rectorBioRu': 'Ректор СДУ',
          'rectorBioKz': 'СДУ ректоры',
          'rectorPhotoUrl': '',
          'leaders': []
        },
        'achievements': [],
        'academicPrograms': [
          {
            'id': 'prog1',
            'name': 'Computer Science',
            'nameRu': 'Информатика',
            'nameKz': 'Информатика',
            'description': 'Bachelor program in Computer Science',
            'descriptionRu': 'Программа бакалавриата по информатике',
            'descriptionKz': 'Информатика бойынша бакалавриат бағдарламасы',
            'degree': 'Bachelor',
            'degreeRu': 'Бакалавр',
            'degreeKz': 'Бакалавр',
            'faculty': 'School of Engineering',
            'facultyRu': 'Инженерная школа',
            'facultyKz': 'Инженерлік мектебі',
            'duration': 4,
            'language': 'Kazakh, Russian, English',
            'languageRu': 'Казахский, Русский, Английский',
            'languageKz': 'Қазақ, Орыс, Ағылшын',
            'tuitionFee': 600000.0,
            'currency': 'KZT',
            'requirements': ['High school diploma', 'Entrance exam'],
            'requirementsRu': ['Аттестат о среднем образовании', 'Вступительные экзамены'],
            'requirementsKz': ['Орта білім туралы куәлік', 'Кіру емтихандары'],
            'careerOpportunities': ['Software Developer', 'IT Specialist'],
            'careerOpportunitiesRu': ['Разработчик ПО', 'IT-специалист'],
            'careerOpportunitiesKz': ['БА дамытушы', 'IT-маман'],
            'imageUrl': '',
            'programCategory': 'engineering'
          }
        ],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'comprehensive',
        'latitude': 43.2000,
        'longitude': 76.8300
      },
      'kazntu': {
        'name': 'Kazakh National Technical University named after K.I. Satpayev',
        'nameRu': 'Казахский национальный технический университет имени К.И. Сатпаева',
        'nameKz': 'К.И. Сәтбаев атындағы Қазақ ұлттық техникалық университеті',
        'description': 'Leading technical university in Kazakhstan',
        'descriptionRu': 'Ведущий технический университет Казахстана, основанный в 1934 году',
        'descriptionKz': '1934 жылы құрылған Қазақстандағы жетекші техникалық университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kazntu.kz',
        'email': 'info@kazntu.kz',
        'phone': '+7 (727) 292-60-00',
        'rating': 4.6,
        'studentCount': 18000,
        'foundedDate': Timestamp.fromDate(DateTime(1934, 1, 1)),
        'images': [],
        'mission': {
          'text': 'To provide world-class technical education',
          'textRu': 'Обеспечение технического образования мирового уровня',
          'textKz': 'Әлемдік деңгейдегі техникалық білім беру',
          'vision': 'Leading technical university',
          'visionRu': 'Ведущий технический университет',
          'visionKz': 'Жетекші техникалық университет',
          'values': ['Excellence', 'Innovation'],
          'valuesRu': ['Превосходство', 'Инновации'],
          'valuesKz': ['Тамаша', 'Инновациялар']
        },
        'history': {
          'text': 'Founded in 1934',
          'textRu': 'Основан в 1934 году',
          'textKz': '1934 жылы құрылды',
          'events': []
        },
        'leadership': {
          'rectorName': 'Meiram Begentayev',
          'rectorNameRu': 'Мейрам Бегентаев',
          'rectorNameKz': 'Мейрам Бегентаев',
          'rectorBio': 'Doctor of Technical Sciences',
          'rectorBioRu': 'Доктор технических наук',
          'rectorBioKz': 'Техника ғылымдарының докторы',
          'rectorPhotoUrl': '',
          'leaders': []
        },
        'achievements': [],
        'academicPrograms': [
          {
            'id': 'prog1',
            'name': 'Mechanical Engineering',
            'nameRu': 'Машиностроение',
            'nameKz': 'Машина жасау',
            'description': 'Bachelor program in Mechanical Engineering',
            'descriptionRu': 'Программа бакалавриата по машиностроению',
            'descriptionKz': 'Машина жасау бойынша бакалавриат бағдарламасы',
            'degree': 'Bachelor',
            'degreeRu': 'Бакалавр',
            'degreeKz': 'Бакалавр',
            'faculty': 'Faculty of Mechanical Engineering',
            'facultyRu': 'Факультет машиностроения',
            'facultyKz': 'Машина жасау факультеті',
            'duration': 4,
            'language': 'Kazakh, Russian',
            'languageRu': 'Казахский, Русский',
            'languageKz': 'Қазақ, Орыс',
            'tuitionFee': 450000.0,
            'currency': 'KZT',
            'requirements': ['High school diploma', 'Entrance exam'],
            'requirementsRu': ['Аттестат о среднем образовании', 'Вступительные экзамены'],
            'requirementsKz': ['Орта білім туралы куәлік', 'Кіру емтихандары'],
            'careerOpportunities': ['Mechanical Engineer', 'Design Engineer'],
            'careerOpportunitiesRu': ['Инженер-механик', 'Инженер-конструктор'],
            'careerOpportunitiesKz': ['Механикалық инженер', 'Конструктор инженер'],
            'imageUrl': '',
            'programCategory': 'engineering'
          }
        ],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'technical',
        'latitude': 43.2300,
        'longitude': 76.8600
      },
      'kazgyu': {
        'name': 'Kazakh Humanitarian Law University',
        'nameRu': 'Казахский гуманитарно-юридический университет',
        'nameKz': 'Қазақ гуманитарлық-заңдық университеті',
        'description': 'Leading law university',
        'descriptionRu': 'Ведущий юридический университет',
        'descriptionKz': 'Жетекші заңдық университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Astana, Kazakhstan',
        'city': 'Астана',
        'website': 'https://www.kazgyu.kz',
        'email': 'info@kazgyu.kz',
        'phone': '+7 (7172) 70-30-10',
        'rating': 4.5,
        'studentCount': 12000,
        'foundedDate': Timestamp.fromDate(DateTime(1994, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Law',
          'nameRu': 'Юриспруденция',
          'nameKz': 'Заң',
          'description': 'Bachelor program in Law',
          'descriptionRu': 'Программа бакалавриата по юриспруденции',
          'descriptionKz': 'Заң бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Law',
          'facultyRu': 'Юридический факультет',
          'facultyKz': 'Заң факультеті',
          'duration': 4,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 550000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Lawyer'],
          'careerOpportunitiesRu': ['Адвокат'],
          'careerOpportunitiesKz': ['Адвокат'],
          'imageUrl': '',
          'programCategory': 'law'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'humanitarian',
        'latitude': 51.1800,
        'longitude': 71.4200
      },
      'kaznpu': {
        'name': 'Abai Kazakh National Pedagogical University',
        'nameRu': 'Казахский национальный педагогический университет имени Абая',
        'nameKz': 'Абай атындағы Қазақ ұлттық педагогикалық университеті',
        'description': 'Leading pedagogical university',
        'descriptionRu': 'Ведущий педагогический университет',
        'descriptionKz': 'Жетекші педагогикалық университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kaznpu.kz',
        'email': 'info@kaznpu.kz',
        'phone': '+7 (727) 291-60-00',
        'rating': 4.4,
        'studentCount': 15000,
        'foundedDate': Timestamp.fromDate(DateTime(1928, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Pedagogy',
          'nameRu': 'Педагогика',
          'nameKz': 'Педагогика',
          'description': 'Bachelor program in Pedagogy',
          'descriptionRu': 'Программа бакалавриата по педагогике',
          'descriptionKz': 'Педагогика бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Pedagogy',
          'facultyRu': 'Педагогический факультет',
          'facultyKz': 'Педагогикалық факультет',
          'duration': 4,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 350000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Teacher'],
          'careerOpportunitiesRu': ['Учитель'],
          'careerOpportunitiesKz': ['Мұғалім'],
          'imageUrl': '',
          'programCategory': 'education'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'pedagogical',
        'latitude': 43.2400,
        'longitude': 76.8700
      },
      'kaznau': {
        'name': 'Kazakh National Agrarian University',
        'nameRu': 'Казахский национальный аграрный университет',
        'nameKz': 'Қазақ ұлттық аграрлық университеті',
        'description': 'Leading agricultural university',
        'descriptionRu': 'Ведущий аграрный университет',
        'descriptionKz': 'Жетекші аграрлық университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kaznau.kz',
        'email': 'info@kaznau.kz',
        'phone': '+7 (727) 377-33-44',
        'rating': 4.3,
        'studentCount': 10000,
        'foundedDate': Timestamp.fromDate(DateTime(1929, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Agronomy',
          'nameRu': 'Агрономия',
          'nameKz': 'Агрономия',
          'description': 'Bachelor program in Agronomy',
          'descriptionRu': 'Программа бакалавриата по агрономии',
          'descriptionKz': 'Агрономия бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Agronomy',
          'facultyRu': 'Агрономический факультет',
          'facultyKz': 'Агрономиялық факультет',
          'duration': 4,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 400000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Agronomist'],
          'careerOpportunitiesRu': ['Агроном'],
          'careerOpportunitiesKz': ['Агроном'],
          'imageUrl': '',
          'programCategory': 'agriculture'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'agricultural',
        'latitude': 43.2500,
        'longitude': 76.8800
      },
      'kaznmu': {
        'name': 'Asfendiyarov Kazakh National Medical University',
        'nameRu': 'Казахский национальный медицинский университет имени С.Д. Асфендиярова',
        'nameKz': 'С.Д. Асфендияров атындағы Қазақ ұлттық медициналық университеті',
        'description': 'Leading medical university',
        'descriptionRu': 'Ведущий медицинский университет',
        'descriptionKz': 'Жетекші медициналық университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kaznmu.kz',
        'email': 'info@kaznmu.kz',
        'phone': '+7 (727) 292-70-00',
        'rating': 4.7,
        'studentCount': 12000,
        'foundedDate': Timestamp.fromDate(DateTime(1930, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'General Medicine',
          'nameRu': 'Общая медицина',
          'nameKz': 'Жалпы медицина',
          'description': 'Bachelor program in General Medicine',
          'descriptionRu': 'Программа бакалавриата по общей медицине',
          'descriptionKz': 'Жалпы медицина бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Medicine',
          'facultyRu': 'Медицинский факультет',
          'facultyKz': 'Медициналық факультет',
          'duration': 5,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 800000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Doctor'],
          'careerOpportunitiesRu': ['Врач'],
          'careerOpportunitiesKz': ['Дәрігер'],
          'imageUrl': '',
          'programCategory': 'medicine'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'medical',
        'latitude': 43.2600,
        'longitude': 76.8900
      },
      'kaznui': {
        'name': 'Kazakh National University of Arts',
        'nameRu': 'Казахский национальный университет искусств',
        'nameKz': 'Қазақ ұлттық өнер университеті',
        'description': 'Leading arts university',
        'descriptionRu': 'Ведущий университет искусств',
        'descriptionKz': 'Жетекші өнер университеті',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Astana, Kazakhstan',
        'city': 'Астана',
        'website': 'https://www.kaznui.kz',
        'email': 'info@kaznui.kz',
        'phone': '+7 (7172) 70-40-10',
        'rating': 4.4,
        'studentCount': 3000,
        'foundedDate': Timestamp.fromDate(DateTime(1998, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Music',
          'nameRu': 'Музыка',
          'nameKz': 'Музыка',
          'description': 'Bachelor program in Music',
          'descriptionRu': 'Программа бакалавриата по музыке',
          'descriptionKz': 'Музыка бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Music',
          'facultyRu': 'Музыкальный факультет',
          'facultyKz': 'Музыкалық факультет',
          'duration': 4,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 500000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Musician'],
          'careerOpportunitiesRu': ['Музыкант'],
          'careerOpportunitiesKz': ['Музыкант'],
          'imageUrl': '',
          'programCategory': 'arts'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'arts',
        'latitude': 51.1900,
        'longitude': 71.4300
      },
      'kazatu': {
        'name': 'Kazakh Academy of Transport and Communications',
        'nameRu': 'Казахская академия транспорта и коммуникаций',
        'nameKz': 'Қазақ көлік және байланыс академиясы',
        'description': 'Leading transport university',
        'descriptionRu': 'Ведущий транспортный университет',
        'descriptionKz': 'Жетекші көлік университеті',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kazatu.kz',
        'email': 'info@kazatu.kz',
        'phone': '+7 (727) 292-80-00',
        'rating': 4.3,
        'studentCount': 8000,
        'foundedDate': Timestamp.fromDate(DateTime(1956, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Transport Engineering',
          'nameRu': 'Транспортная инженерия',
          'nameKz': 'Көлік инженериясы',
          'description': 'Bachelor program in Transport Engineering',
          'descriptionRu': 'Программа бакалавриата по транспортной инженерии',
          'descriptionKz': 'Көлік инженериясы бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Transport',
          'facultyRu': 'Транспортный факультет',
          'facultyKz': 'Көлік факультеті',
          'duration': 4,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 450000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Transport Engineer'],
          'careerOpportunitiesRu': ['Инженер транспорта'],
          'careerOpportunitiesKz': ['Көлік инженері'],
          'imageUrl': '',
          'programCategory': 'engineering'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'technical',
        'latitude': 43.2700,
        'longitude': 76.9000
      },
      'kazumo': {
        'name': 'Kazakh University of International Relations and World Languages',
        'nameRu': 'Казахский университет международных отношений и мировых языков',
        'nameKz': 'Қазақ халықаралық қатынастар және әлем тілдері университеті',
        'description': 'Leading international relations university',
        'descriptionRu': 'Ведущий университет международных отношений',
        'descriptionKz': 'Жетекші халықаралық қатынастар университеті',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kazumo.kz',
        'email': 'info@kazumo.kz',
        'phone': '+7 (727) 292-90-00',
        'rating': 4.4,
        'studentCount': 6000,
        'foundedDate': Timestamp.fromDate(DateTime(2000, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'International Relations',
          'nameRu': 'Международные отношения',
          'nameKz': 'Халықаралық қатынастар',
          'description': 'Bachelor program in International Relations',
          'descriptionRu': 'Программа бакалавриата по международным отношениям',
          'descriptionKz': 'Халықаралық қатынастар бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of International Relations',
          'facultyRu': 'Факультет международных отношений',
          'facultyKz': 'Халықаралық қатынастар факультеті',
          'duration': 4,
          'language': 'Kazakh, Russian, English',
          'languageRu': 'Казахский, Русский, Английский',
          'languageKz': 'Қазақ, Орыс, Ағылшын',
          'tuitionFee': 600000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Diplomat'],
          'careerOpportunitiesRu': ['Дипломат'],
          'careerOpportunitiesKz': ['Дипломат'],
          'imageUrl': '',
          'programCategory': 'humanitarian'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'humanitarian',
        'latitude': 43.2800,
        'longitude': 76.9100
      },
      'kaznutik': {
        'name': 'Kazakh National University of Tourism and Service',
        'nameRu': 'Казахский национальный университет туризма и сервиса',
        'nameKz': 'Қазақ ұлттық туризм және сервис университеті',
        'description': 'Leading tourism university',
        'descriptionRu': 'Ведущий университет туризма',
        'descriptionKz': 'Жетекші туризм университеті',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Shymkent, Kazakhstan',
        'city': 'Шымкент',
        'website': 'https://www.kaznutik.kz',
        'email': 'info@kaznutik.kz',
        'phone': '+7 (7252) 21-00-00',
        'rating': 4.2,
        'studentCount': 5000,
        'foundedDate': Timestamp.fromDate(DateTime(2000, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Tourism',
          'nameRu': 'Туризм',
          'nameKz': 'Туризм',
          'description': 'Bachelor program in Tourism',
          'descriptionRu': 'Программа бакалавриата по туризму',
          'descriptionKz': 'Туризм бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Tourism',
          'facultyRu': 'Факультет туризма',
          'facultyKz': 'Туризм факультеті',
          'duration': 4,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 400000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Tourism Manager'],
          'careerOpportunitiesRu': ['Менеджер по туризму'],
          'careerOpportunitiesKz': ['Туризм менеджері'],
          'imageUrl': '',
          'programCategory': 'business'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'economic',
        'latitude': 42.3000,
        'longitude': 69.6000
      },
      'kaznue': {
        'name': 'Kazakh National University of Economics',
        'nameRu': 'Казахский национальный университет экономики',
        'nameKz': 'Қазақ ұлттық экономика университеті',
        'description': 'Leading economics university',
        'descriptionRu': 'Ведущий экономический университет',
        'descriptionKz': 'Жетекші экономикалық университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kaznue.kz',
        'email': 'info@kaznue.kz',
        'phone': '+7 (727) 377-33-55',
        'rating': 4.5,
        'studentCount': 14000,
        'foundedDate': Timestamp.fromDate(DateTime(1963, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Economics',
          'nameRu': 'Экономика',
          'nameKz': 'Экономика',
          'description': 'Bachelor program in Economics',
          'descriptionRu': 'Программа бакалавриата по экономике',
          'descriptionKz': 'Экономика бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Economics',
          'facultyRu': 'Экономический факультет',
          'facultyKz': 'Экономикалық факультет',
          'duration': 4,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 500000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Economist'],
          'careerOpportunitiesRu': ['Экономист'],
          'careerOpportunitiesKz': ['Экономист'],
          'imageUrl': '',
          'programCategory': 'business'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'economic',
        'latitude': 43.2900,
        'longitude': 76.9200
      },
      'kaznupt': {
        'name': 'Kazakh National University of Polytechnic',
        'nameRu': 'Казахский национальный политехнический университет',
        'nameKz': 'Қазақ ұлттық политехникалық университеті',
        'description': 'Leading polytechnic university',
        'descriptionRu': 'Ведущий политехнический университет',
        'descriptionKz': 'Жетекші политехникалық университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kaznupt.kz',
        'email': 'info@kaznupt.kz',
        'phone': '+7 (727) 377-33-66',
        'rating': 4.4,
        'studentCount': 16000,
        'foundedDate': Timestamp.fromDate(DateTime(1960, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Electrical Engineering',
          'nameRu': 'Электротехника',
          'nameKz': 'Электр техникасы',
          'description': 'Bachelor program in Electrical Engineering',
          'descriptionRu': 'Программа бакалавриата по электротехнике',
          'descriptionKz': 'Электр техникасы бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Electrical Engineering',
          'facultyRu': 'Электротехнический факультет',
          'facultyKz': 'Электр техникалық факультет',
          'duration': 4,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 480000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Electrical Engineer'],
          'careerOpportunitiesRu': ['Инженер-электрик'],
          'careerOpportunitiesKz': ['Электр инженері'],
          'imageUrl': '',
          'programCategory': 'engineering'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'technical',
        'latitude': 43.3000,
        'longitude': 76.9300
      },
      'kaznufkis': {
        'name': 'Kazakh National University of Physical Culture and Sports',
        'nameRu': 'Казахский национальный университет физической культуры и спорта',
        'nameKz': 'Қазақ ұлттық дене шынықтыру және спорт университеті',
        'description': 'Leading sports university',
        'descriptionRu': 'Ведущий университет физической культуры',
        'descriptionKz': 'Жетекші дене шынықтыру университеті',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kaznufkis.kz',
        'email': 'info@kaznufkis.kz',
        'phone': '+7 (727) 377-33-77',
        'rating': 4.3,
        'studentCount': 4000,
        'foundedDate': Timestamp.fromDate(DateTime(1945, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Physical Culture',
          'nameRu': 'Физическая культура',
          'nameKz': 'Дене шынықтыру',
          'description': 'Bachelor program in Physical Culture',
          'descriptionRu': 'Программа бакалавриата по физической культуре',
          'descriptionKz': 'Дене шынықтыру бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Physical Culture',
          'facultyRu': 'Факультет физической культуры',
          'facultyKz': 'Дене шынықтыру факультеті',
          'duration': 4,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 350000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Sports Coach'],
          'careerOpportunitiesRu': ['Тренер'],
          'careerOpportunitiesKz': ['Жаттықтырушы'],
          'imageUrl': '',
          'programCategory': 'science'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'comprehensive',
        'latitude': 43.3100,
        'longitude': 76.9400
      },
      'kaznuv': {
        'name': 'Kazakh National Agrarian Research University',
        'nameRu': 'Казахский национальный аграрный исследовательский университет',
        'nameKz': 'Қазақ ұлттық аграрлық зерттеу университеті',
        'description': 'Leading veterinary university',
        'descriptionRu': 'Ведущий ветеринарный университет',
        'descriptionKz': 'Жетекші ветеринариялық университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kaznuv.kz',
        'email': 'info@kaznuv.kz',
        'phone': '+7 (727) 377-33-88',
        'rating': 4.3,
        'studentCount': 6000,
        'foundedDate': Timestamp.fromDate(DateTime(1929, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Veterinary Medicine',
          'nameRu': 'Ветеринария',
          'nameKz': 'Ветеринария',
          'description': 'Bachelor program in Veterinary Medicine',
          'descriptionRu': 'Программа бакалавриата по ветеринарии',
          'descriptionKz': 'Ветеринария бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Veterinary Medicine',
          'facultyRu': 'Ветеринарный факультет',
          'facultyKz': 'Ветеринариялық факультет',
          'duration': 5,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 500000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Veterinarian'],
          'careerOpportunitiesRu': ['Ветеринар'],
          'careerOpportunitiesKz': ['Ветеринар'],
          'imageUrl': '',
          'programCategory': 'medicine'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'agricultural',
        'latitude': 43.3200,
        'longitude': 76.9500
      },
      'kaznuh': {
        'name': 'Kazakh National University of Chemistry and Technology',
        'nameRu': 'Казахский национальный химико-технологический университет',
        'nameKz': 'Қазақ ұлттық химия-технологиялық университеті',
        'description': 'Leading chemical technology university',
        'descriptionRu': 'Ведущий химико-технологический университет',
        'descriptionKz': 'Жетекші химия-технологиялық университет',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kaznuh.kz',
        'email': 'info@kaznuh.kz',
        'phone': '+7 (727) 377-33-99',
        'rating': 4.4,
        'studentCount': 7000,
        'foundedDate': Timestamp.fromDate(DateTime(1958, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Chemical Engineering',
          'nameRu': 'Химическая инженерия',
          'nameKz': 'Химиялық инженерия',
          'description': 'Bachelor program in Chemical Engineering',
          'descriptionRu': 'Программа бакалавриата по химической инженерии',
          'descriptionKz': 'Химиялық инженерия бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Chemical Engineering',
          'facultyRu': 'Факультет химической инженерии',
          'facultyKz': 'Химиялық инженерия факультеті',
          'duration': 4,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 470000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Chemical Engineer'],
          'careerOpportunitiesRu': ['Инженер-химик'],
          'careerOpportunitiesKz': ['Химиялық инженер'],
          'imageUrl': '',
          'programCategory': 'engineering'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'technical',
        'latitude': 43.3300,
        'longitude': 76.9600
      },
      'kaznus': {
        'name': 'Kazakh National University of Construction and Architecture',
        'nameRu': 'Казахский национальный университет строительства и архитектуры',
        'nameKz': 'Қазақ ұлттық құрылыс және сәулет университеті',
        'description': 'Leading construction university',
        'descriptionRu': 'Ведущий строительный университет',
        'descriptionKz': 'Жетекші құрылыс университеті',
        'logoUrl': '',
        'coverImageUrl': '',
        'location': 'Almaty, Kazakhstan',
        'city': 'Алматы',
        'website': 'https://www.kaznus.kz',
        'email': 'info@kaznus.kz',
        'phone': '+7 (727) 377-34-00',
        'rating': 4.3,
        'studentCount': 9000,
        'foundedDate': Timestamp.fromDate(DateTime(1961, 1, 1)),
        'images': [],
        'mission': _getMissionTemplate('humanitarian'),
        'history': _getHistoryTemplate('Казахский гуманитарно-юридический университет', 1994),
        'leadership': _getLeadershipTemplate(),
        'achievements': [],
        'academicPrograms': [{
          'id': 'prog1',
          'name': 'Architecture',
          'nameRu': 'Архитектура',
          'nameKz': 'Сәулет',
          'description': 'Bachelor program in Architecture',
          'descriptionRu': 'Программа бакалавриата по архитектуре',
          'descriptionKz': 'Сәулет бойынша бакалавриат бағдарламасы',
          'degree': 'Bachelor',
          'degreeRu': 'Бакалавр',
          'degreeKz': 'Бакалавр',
          'faculty': 'Faculty of Architecture',
          'facultyRu': 'Архитектурный факультет',
          'facultyKz': 'Сәулет факультеті',
          'duration': 5,
          'language': 'Kazakh, Russian',
          'languageRu': 'Казахский, Русский',
          'languageKz': 'Қазақ, Орыс',
          'tuitionFee': 550000.0,
          'currency': 'KZT',
          'requirements': ['High school diploma'],
          'requirementsRu': ['Аттестат о среднем образовании'],
          'requirementsKz': ['Орта білім туралы куәлік'],
          'careerOpportunities': ['Architect'],
          'careerOpportunitiesRu': ['Архитектор'],
          'careerOpportunitiesKz': ['Сәулетші'],
          'imageUrl': '',
          'programCategory': 'engineering'
        }],
        'internationalCooperation': _getInternationalCooperationTemplate(),
        'admission': _getAdmissionTemplate(),
        'tour3dUrl': '',
        'universityType': 'technical',
        'latitude': 43.3400,
        'longitude': 76.9700
      }
    };
  }
}

